# Generated by Django 5.2.17 on 2026-10-03 13:40

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='ФИО')),
                ('short_name', models.CharField(help_text='Например «Ким».', max_length=60, unique=True, verbose_name='как в шахматке')),
                ('display_order', models.PositiveSmallIntegerField(default=0, verbose_name='порядок в шахматке')),
                ('is_active', models.BooleanField(default=True, verbose_name='работает')),
                ('partner', models.OneToOneField(blank=True, help_text='Напарники работают в одной колонке шахматки. Связь ставится с обеих сторон.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='staff.instructor', verbose_name='напарник по 2/2')),
            ],
            options={
                'verbose_name': 'инструктор',
                'verbose_name_plural': 'инструкторы',
                'ordering': ['display_order', 'short_name'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalInstructor',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='ФИО')),
                ('short_name', models.CharField(db_index=True, help_text='Например «Ким».', max_length=60, verbose_name='как в шахматке')),
                ('display_order', models.PositiveSmallIntegerField(default=0, verbose_name='порядок в шахматке')),
                ('is_active', models.BooleanField(default=True, verbose_name='работает')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(blank=True, db_constraint=False, help_text='Напарники работают в одной колонке шахматки. Связь ставится с обеих сторон.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='staff.instructor', verbose_name='напарник по 2/2')),
            ],
            options={
                'verbose_name': 'historical инструктор',
                'verbose_name_plural': 'historical инструкторы',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
