# Generated by Django 5.2.17 on 2026-10-04 13:53

import apps.staff.models
import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.contrib.postgres.operations import BtreeGistExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_procedure_group_choice'),
        ('staff', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Ограничения «периоды не пересекаются» сравнивают instructor/slot через GiST.
        BtreeGistExtension(),
        migrations.CreateModel(
            name='HistoricalInstructorBlock',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('label', models.CharField(blank=True, help_text='Для «Прочее».', max_length=60, verbose_name='подпись')),
                ('date', models.DateField(verbose_name='дата')),
                ('kind', models.CharField(choices=[('METHOD_WORK', 'Метод. работа'), ('GROUP_LEAD', 'Ведение группы'), ('BOS', 'БОС'), ('OTHER', 'Прочее'), ('CLEAR', 'Снять распорядок в этот день')], max_length=20, verbose_name='вид')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('group_session', models.ForeignKey(blank=True, db_constraint=False, help_text='Только для ведения группы.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalog.groupsession', verbose_name='занятие группы')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('instructor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='staff.instructor', verbose_name='инструктор')),
                ('slot', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalog.instructorslot', verbose_name='слот')),
            ],
            options={
                'verbose_name': 'historical разовый блок',
                'verbose_name_plural': 'historical разовые блоки',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalInstructorDuty',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('valid_from', models.DateField(verbose_name='действует с')),
                ('valid_to', models.DateField(blank=True, help_text='Пусто — бессрочно.', null=True, verbose_name='действует по')),
                ('label', models.CharField(blank=True, help_text='Для «Прочее».', max_length=60, verbose_name='подпись')),
                ('kind', models.CharField(choices=[('METHOD_WORK', 'Метод. работа'), ('GROUP_LEAD', 'Ведение группы'), ('BOS', 'БОС'), ('OTHER', 'Прочее')], max_length=20, verbose_name='вид')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('group_session', models.ForeignKey(blank=True, db_constraint=False, help_text='Только для ведения группы.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalog.groupsession', verbose_name='занятие группы')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('instructor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='staff.instructor', verbose_name='инструктор')),
                ('slot', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalog.instructorslot', verbose_name='слот')),
            ],
            options={
                'verbose_name': 'historical обязанность распорядка',
                'verbose_name_plural': 'historical распорядок инструкторов',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalShiftException',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('date', models.DateField(verbose_name='дата')),
                ('is_working', models.BooleanField(verbose_name='работает')),
                ('reason', models.CharField(blank=True, max_length=100, verbose_name='причина')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('instructor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='staff.instructor', verbose_name='инструктор')),
            ],
            options={
                'verbose_name': 'historical исключение из смены',
                'verbose_name_plural': 'historical исключения из смен',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalShiftPattern',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('valid_from', models.DateField(verbose_name='действует с')),
                ('valid_to', models.DateField(blank=True, help_text='Пусто — бессрочно.', null=True, verbose_name='действует по')),
                ('pattern', models.CharField(choices=[('2/2', '2/2'), ('5/2', '5/2 (пн–пт)'), ('daily', 'каждый день')], max_length=10, verbose_name='шаблон')),
                ('anchor_date', models.DateField(help_text='Для 2/2: любой первый день из двух рабочих.', verbose_name='первый рабочий день цикла')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('instructor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='staff.instructor', verbose_name='инструктор')),
            ],
            options={
                'verbose_name': 'historical шаблон смены',
                'verbose_name_plural': 'historical шаблоны смен',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='InstructorBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, help_text='Для «Прочее».', max_length=60, verbose_name='подпись')),
                ('date', models.DateField(verbose_name='дата')),
                ('kind', models.CharField(choices=[('METHOD_WORK', 'Метод. работа'), ('GROUP_LEAD', 'Ведение группы'), ('BOS', 'БОС'), ('OTHER', 'Прочее'), ('CLEAR', 'Снять распорядок в этот день')], max_length=20, verbose_name='вид')),
                ('group_session', models.ForeignKey(blank=True, help_text='Только для ведения группы.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.groupsession', verbose_name='занятие группы')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blocks', to='staff.instructor', verbose_name='инструктор')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.instructorslot', verbose_name='слот')),
            ],
            options={
                'verbose_name': 'разовый блок',
                'verbose_name_plural': 'разовые блоки',
                'ordering': ['date', 'slot__start', 'instructor'],
                'constraints': [models.UniqueConstraint(fields=('instructor', 'date', 'slot'), name='unique_instructor_block')],
            },
        ),
        migrations.CreateModel(
            name='InstructorDuty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', models.DateField(verbose_name='действует с')),
                ('valid_to', models.DateField(blank=True, help_text='Пусто — бессрочно.', null=True, verbose_name='действует по')),
                ('label', models.CharField(blank=True, help_text='Для «Прочее».', max_length=60, verbose_name='подпись')),
                ('kind', models.CharField(choices=[('METHOD_WORK', 'Метод. работа'), ('GROUP_LEAD', 'Ведение группы'), ('BOS', 'БОС'), ('OTHER', 'Прочее')], max_length=20, verbose_name='вид')),
                ('group_session', models.ForeignKey(blank=True, help_text='Только для ведения группы.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.groupsession', verbose_name='занятие группы')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='duties', to='staff.instructor', verbose_name='инструктор')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.instructorslot', verbose_name='слот')),
            ],
            options={
                'verbose_name': 'обязанность распорядка',
                'verbose_name_plural': 'распорядок инструкторов',
                'ordering': ['instructor', 'slot__start', 'valid_from'],
                'constraints': [models.CheckConstraint(condition=models.Q(('valid_to__isnull', True), ('valid_to__gte', models.F('valid_from')), _connector='OR'), name='instructor_duty_period_valid'), django.contrib.postgres.constraints.ExclusionConstraint(expressions=[('instructor', '='), ('slot', '='), (apps.staff.models.DateRange(models.F('valid_from'), models.F('valid_to'), django.contrib.postgres.fields.ranges.RangeBoundary(inclusive_upper=True)), '&&')], name='instructor_duty_no_overlap', violation_error_message='В этом слоте у инструктора уже есть обязанность.')],
            },
        ),
        migrations.CreateModel(
            name='ShiftException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='дата')),
                ('is_working', models.BooleanField(verbose_name='работает')),
                ('reason', models.CharField(blank=True, max_length=100, verbose_name='причина')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shift_exceptions', to='staff.instructor', verbose_name='инструктор')),
            ],
            options={
                'verbose_name': 'исключение из смены',
                'verbose_name_plural': 'исключения из смен',
                'ordering': ['date', 'instructor'],
                'constraints': [models.UniqueConstraint(fields=('instructor', 'date'), name='unique_shift_exception')],
            },
        ),
        migrations.CreateModel(
            name='ShiftPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', models.DateField(verbose_name='действует с')),
                ('valid_to', models.DateField(blank=True, help_text='Пусто — бессрочно.', null=True, verbose_name='действует по')),
                ('pattern', models.CharField(choices=[('2/2', '2/2'), ('5/2', '5/2 (пн–пт)'), ('daily', 'каждый день')], max_length=10, verbose_name='шаблон')),
                ('anchor_date', models.DateField(help_text='Для 2/2: любой первый день из двух рабочих.', verbose_name='первый рабочий день цикла')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shift_patterns', to='staff.instructor', verbose_name='инструктор')),
            ],
            options={
                'verbose_name': 'шаблон смены',
                'verbose_name_plural': 'шаблоны смен',
                'ordering': ['instructor', 'valid_from'],
                'constraints': [models.CheckConstraint(condition=models.Q(('valid_to__isnull', True), ('valid_to__gte', models.F('valid_from')), _connector='OR'), name='shift_pattern_period_valid'), django.contrib.postgres.constraints.ExclusionConstraint(expressions=[('instructor', '='), (apps.staff.models.DateRange(models.F('valid_from'), models.F('valid_to'), django.contrib.postgres.fields.ranges.RangeBoundary(inclusive_upper=True)), '&&')], name='shift_pattern_no_overlap', violation_error_message='Периоды шаблонов смен инструктора пересекаются.')],
            },
        ),
    ]
