# Generated by Django 5.2.17 on 2026-10-03 15:26

import django.core.validators
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('org', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalProgram',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='ФИО')),
                ('sex', models.CharField(blank=True, choices=[('М', 'мужской'), ('Ж', 'женский')], help_text='При импорте определяется по отчеству.', max_length=1, verbose_name='пол')),
                ('age', models.PositiveSmallIntegerField(blank=True, help_text='Необязательно. Без возраста в карте печатается только пол.', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)], verbose_name='возраст')),
                ('history_number', models.CharField(blank=True, max_length=20, verbose_name='№ ИБ')),
                ('room', models.CharField(help_text='Например «9» или «5а».', max_length=10, verbose_name='палата')),
                ('shrm', models.PositiveSmallIntegerField(choices=[(3, '3'), (4, '4'), (5, '5')], verbose_name='ШРМ')),
                ('diagnosis', models.CharField(blank=True, max_length=255, verbose_name='диагноз')),
                ('start_date', models.DateField(verbose_name='начало курса')),
                ('end_date', models.DateField(verbose_name='окончание курса')),
                ('end_date_manual', models.BooleanField(default=False, help_text='Если нет — дата пересчитывается при смене ШРМ или начала курса.', verbose_name='окончание задано вручную')),
                ('source', models.CharField(choices=[('import', 'лист назначений'), ('manual', 'вручную')], default='manual', max_length=10, verbose_name='создана')),
                ('import_warnings', models.JSONField(blank=True, default=list, verbose_name='проверить после импорта')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='создана')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='изменена')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('attending_doctor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='лечащий врач')),
                ('department', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='org.department', verbose_name='отделение')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical индивидуальная программа',
                'verbose_name_plural': 'historical индивидуальные программы',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='ФИО')),
                ('sex', models.CharField(blank=True, choices=[('М', 'мужской'), ('Ж', 'женский')], help_text='При импорте определяется по отчеству.', max_length=1, verbose_name='пол')),
                ('age', models.PositiveSmallIntegerField(blank=True, help_text='Необязательно. Без возраста в карте печатается только пол.', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)], verbose_name='возраст')),
                ('history_number', models.CharField(blank=True, max_length=20, verbose_name='№ ИБ')),
                ('room', models.CharField(help_text='Например «9» или «5а».', max_length=10, verbose_name='палата')),
                ('shrm', models.PositiveSmallIntegerField(choices=[(3, '3'), (4, '4'), (5, '5')], verbose_name='ШРМ')),
                ('diagnosis', models.CharField(blank=True, max_length=255, verbose_name='диагноз')),
                ('start_date', models.DateField(verbose_name='начало курса')),
                ('end_date', models.DateField(verbose_name='окончание курса')),
                ('end_date_manual', models.BooleanField(default=False, help_text='Если нет — дата пересчитывается при смене ШРМ или начала курса.', verbose_name='окончание задано вручную')),
                ('source', models.CharField(choices=[('import', 'лист назначений'), ('manual', 'вручную')], default='manual', max_length=10, verbose_name='создана')),
                ('import_warnings', models.JSONField(blank=True, default=list, verbose_name='проверить после импорта')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменена')),
                ('attending_doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programs', to=settings.AUTH_USER_MODEL, verbose_name='лечащий врач')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programs', to='org.department', verbose_name='отделение')),
            ],
            options={
                'verbose_name': 'индивидуальная программа',
                'verbose_name_plural': 'индивидуальные программы',
                'ordering': ['room', 'full_name'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_text', models.TextField(blank=True, verbose_name='текст из листа назначений')),
                ('duration_min', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='длительность, мин')),
                ('per_day', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='раз в день')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='с даты')),
                ('cancel_date', models.DateField(blank=True, help_text='Первый день без процедуры.', null=True, verbose_name='отменено с даты')),
                ('in_card', models.BooleanField(default=True, verbose_name='в карту')),
                ('card_order', models.PositiveIntegerField(default=0, verbose_name='порядок в карте')),
                ('procedure', models.ForeignKey(blank=True, help_text='Пусто — строка из листа назначений не распознана.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='catalog.procedure', verbose_name='процедура')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='programs.program', verbose_name='программа')),
            ],
            options={
                'verbose_name': 'назначение',
                'verbose_name_plural': 'назначения',
                'ordering': ['card_order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalPrescription',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('raw_text', models.TextField(blank=True, verbose_name='текст из листа назначений')),
                ('duration_min', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='длительность, мин')),
                ('per_day', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='раз в день')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='с даты')),
                ('cancel_date', models.DateField(blank=True, help_text='Первый день без процедуры.', null=True, verbose_name='отменено с даты')),
                ('in_card', models.BooleanField(default=True, verbose_name='в карту')),
                ('card_order', models.PositiveIntegerField(default=0, verbose_name='порядок в карте')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('procedure', models.ForeignKey(blank=True, db_constraint=False, help_text='Пусто — строка из листа назначений не распознана.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalog.procedure', verbose_name='процедура')),
                ('program', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='programs.program', verbose_name='программа')),
            ],
            options={
                'verbose_name': 'historical назначение',
                'verbose_name_plural': 'historical назначения',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddIndex(
            model_name='program',
            index=models.Index(fields=['department', 'end_date'], name='programs_pr_departm_dee117_idx'),
        ),
        migrations.AddConstraint(
            model_name='program',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='program_end_not_before_start', violation_error_message='Окончание курса не может быть раньше начала.'),
        ),
    ]
