# Generated by Django 5.2.17 on 2026-10-03 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprogram',
            name='schedule_issues',
            field=models.JSONField(blank=True, default=list, help_text='Конфликты и предупреждения последнего подбора: [{code, message, conflict}].', verbose_name='проблемы расписания'),
        ),
        migrations.AddField(
            model_name='program',
            name='schedule_issues',
            field=models.JSONField(blank=True, default=list, help_text='Конфликты и предупреждения последнего подбора: [{code, message, conflict}].', verbose_name='проблемы расписания'),
        ),
    ]
