# Generated by Django 5.2.17 on 2026-10-04 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('programs', '0002_historicalprogram_schedule_issues_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprescription',
            name='pool_group',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Для назначения «Бассейн» без группы; выбирает специалист ФР.', limit_choices_to={'kind': 'POOL'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalog.procedure', verbose_name='группа бассейна'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='pool_group',
            field=models.ForeignKey(blank=True, help_text='Для назначения «Бассейн» без группы; выбирает специалист ФР.', limit_choices_to={'kind': 'POOL'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pool_prescriptions', to='catalog.procedure', verbose_name='группа бассейна'),
        ),
    ]
