# Generated by Django 5.2.17 on 2026-10-04 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_prescription_pool_group'),
        ('staff', '0002_shifts_and_duties'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprogram',
            name='preferred_instructor',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='staff.instructor', verbose_name='инструктор по желанию пациента'),
        ),
        migrations.AddField(
            model_name='program',
            name='preferred_instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='preferred_by', to='staff.instructor', verbose_name='инструктор по желанию пациента'),
        ),
    ]
