# Generated by Django 5.2.17 on 2026-10-06 04:09

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0004_historicalprogram_preferred_instructor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalWithdrawal',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('date_from', models.DateField(help_text='Первый день без занятий.', verbose_name='выбыл с')),
                ('reason', models.CharField(choices=[('early_discharge', 'досрочная выписка'), ('refusal', 'отказ'), ('transfer', 'перевод'), ('left', 'самовольный уход'), ('other', 'другое')], max_length=20, verbose_name='причина')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='комментарий')),
                ('returned_on', models.DateField(blank=True, null=True, verbose_name='восстановлен с')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='отмечено')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='programs.program', verbose_name='программа')),
            ],
            options={
                'verbose_name': 'historical выбытие',
                'verbose_name_plural': 'historical выбытия',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField(help_text='Первый день без занятий.', verbose_name='выбыл с')),
                ('reason', models.CharField(choices=[('early_discharge', 'досрочная выписка'), ('refusal', 'отказ'), ('transfer', 'перевод'), ('left', 'самовольный уход'), ('other', 'другое')], max_length=20, verbose_name='причина')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='комментарий')),
                ('returned_on', models.DateField(blank=True, null=True, verbose_name='восстановлен с')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='отмечено')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='programs.program', verbose_name='программа')),
            ],
            options={
                'verbose_name': 'выбытие',
                'verbose_name_plural': 'выбытия',
                'ordering': ['date_from'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('returned_on__isnull', True)), fields=('program',), name='withdrawal_one_open_per_program')],
            },
        ),
    ]
