# Generated by Django 5.2.17 on 2026-10-06 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0005_withdrawal'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprogram',
            name='previous',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='programs.program', verbose_name='прошлый курс'),
        ),
        migrations.AddField(
            model_name='program',
            name='previous',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_courses', to='programs.program', verbose_name='прошлый курс'),
        ),
    ]
