# Generated by Django 5.2.17 on 2026-10-06 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0006_program_previous'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalprogram',
            name='preferred_instructor',
        ),
        migrations.RemoveField(
            model_name='program',
            name='preferred_instructor',
        ),
    ]
