# Generated by Django 5.2.17 on 2026-10-03 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CardExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='когда')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_exports', to='programs.program', verbose_name='программа')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='кто выгрузил')),
            ],
            options={
                'verbose_name': 'выгрузка карты',
                'verbose_name_plural': 'выгрузки карт',
                'ordering': ['-created_at'],
            },
        ),
    ]
