# Generated by Django 5.2.17 on 2026-10-03 16:27

import apps.scheduling.models
import django.contrib.postgres.constraints
import django.db.models.deletion
from django.contrib.postgres.operations import BtreeGistExtension
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('programs', '0002_historicalprogram_schedule_issues_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Ограничение «пациент не в двух местах сразу» сравнивает program через GiST.
        BtreeGistExtension(),
        migrations.CreateModel(
            name='HistoricalBooking',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('kind', models.CharField(choices=[('LFK_GROUP', 'Lfk Group'), ('POOL', 'Pool'), ('INDIVIDUAL', 'Individual'), ('EQUIPMENT', 'Equipment')], max_length=20, verbose_name='вид')),
                ('date', models.DateField(verbose_name='дата')),
                ('start', models.TimeField(verbose_name='начало')),
                ('end', models.TimeField(verbose_name='конец')),
                ('note', models.CharField(blank=True, max_length=100, verbose_name='пометка')),
                ('source', models.CharField(choices=[('auto', 'подбор'), ('manual', 'вручную'), ('import', 'импорт')], default='auto', max_length=10, verbose_name='источник')),
                ('pinned', models.BooleanField(default=False, help_text='Поставлено вручную — подбор его не трогает.', verbose_name='закреплено')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='версия')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('equipment', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalog.equipment', verbose_name='тренажёр')),
                ('group_session', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalog.groupsession', verbose_name='занятие группы')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('prescription', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='programs.prescription', verbose_name='назначение')),
                ('procedure', models.ForeignKey(blank=True, db_constraint=False, help_text='Для бассейна без группы в назначении — выбранная группа бассейна.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalog.procedure', verbose_name='процедура')),
                ('program', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='programs.program', verbose_name='программа')),
            ],
            options={
                'verbose_name': 'historical занятие',
                'verbose_name_plural': 'historical занятия',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('LFK_GROUP', 'Lfk Group'), ('POOL', 'Pool'), ('INDIVIDUAL', 'Individual'), ('EQUIPMENT', 'Equipment')], max_length=20, verbose_name='вид')),
                ('date', models.DateField(verbose_name='дата')),
                ('start', models.TimeField(verbose_name='начало')),
                ('end', models.TimeField(verbose_name='конец')),
                ('note', models.CharField(blank=True, max_length=100, verbose_name='пометка')),
                ('source', models.CharField(choices=[('auto', 'подбор'), ('manual', 'вручную'), ('import', 'импорт')], default='auto', max_length=10, verbose_name='источник')),
                ('pinned', models.BooleanField(default=False, help_text='Поставлено вручную — подбор его не трогает.', verbose_name='закреплено')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='версия')),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='catalog.equipment', verbose_name='тренажёр')),
                ('group_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='catalog.groupsession', verbose_name='занятие группы')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='programs.prescription', verbose_name='назначение')),
                ('procedure', models.ForeignKey(help_text='Для бассейна без группы в назначении — выбранная группа бассейна.', on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='catalog.procedure', verbose_name='процедура')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='programs.program', verbose_name='программа')),
            ],
            options={
                'verbose_name': 'занятие',
                'verbose_name_plural': 'занятия',
                'ordering': ['date', 'start'],
                'indexes': [models.Index(fields=['equipment', 'date'], name='scheduling__equipme_28bbd3_idx'), models.Index(fields=['program', 'date'], name='scheduling__program_901a5c_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('end__gt', models.F('start'))), name='booking_end_after_start'), django.contrib.postgres.constraints.ExclusionConstraint(expressions=[('program', '='), (apps.scheduling.models.BookingPeriod(models.F('date'), models.F('start'), models.F('end')), '&&')], name='booking_patient_not_in_two_places', violation_error_message='У пациента уже есть занятие в это время.')],
            },
        ),
    ]
