# Generated by Django 5.2.17 on 2026-10-04 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_procedure_group_choice'),
        ('programs', '0004_historicalprogram_preferred_instructor_and_more'),
        ('scheduling', '0001_initial'),
        ('staff', '0002_shifts_and_duties'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='staff.instructor', verbose_name='инструктор'),
        ),
        migrations.AddField(
            model_name='booking',
            name='slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='catalog.instructorslot', verbose_name='слот'),
        ),
        migrations.AddField(
            model_name='historicalbooking',
            name='instructor',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='staff.instructor', verbose_name='инструктор'),
        ),
        migrations.AddField(
            model_name='historicalbooking',
            name='slot',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalog.instructorslot', verbose_name='слот'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['instructor', 'date'], name='scheduling__instruc_fe936a_idx'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('instructor__isnull', False), ('kind', 'INDIVIDUAL'), ('slot__isnull', False)), models.Q(models.Q(('kind', 'INDIVIDUAL'), _negated=True), ('instructor__isnull', True), ('slot__isnull', True)), _connector='OR'), name='booking_instructor_only_individual'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'INDIVIDUAL')), fields=('instructor', 'date', 'slot'), name='booking_instructor_slot_unique', violation_error_message='У инструктора уже есть пациент в этом слоте.'),
        ),
    ]
