# Generated by Django 5.2.17 on 2026-10-05 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_procedure_group_choice'),
        ('programs', '0004_historicalprogram_preferred_instructor_and_more'),
        ('scheduling', '0002_booking_instructor_booking_slot_and_more'),
        ('staff', '0002_shifts_and_duties'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='booking',
            name='booking_instructor_only_individual',
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'INDIVIDUAL'), ('slot__isnull', False), models.Q(('instructor__isnull', False), ('date__iso_week_day__gte', 6), _connector='OR')), models.Q(models.Q(('kind', 'INDIVIDUAL'), _negated=True), ('instructor__isnull', True), ('slot__isnull', True)), _connector='OR'), name='booking_instructor_only_individual'),
        ),
    ]
