# Generated by Django 5.2.17 on 2026-10-05 04:29

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0004_historicalprogram_preferred_instructor_and_more'),
        ('scheduling', '0003_individual_weekend_without_instructor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalRemovedSession',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('date', models.DateField(verbose_name='дата')),
                ('units', models.PositiveSmallIntegerField(default=1, verbose_name='сколько занятий убрано')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('prescription', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='programs.prescription', verbose_name='назначение')),
            ],
            options={
                'verbose_name': 'historical убранное занятие',
                'verbose_name_plural': 'historical убранные занятия',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='RemovedSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='дата')),
                ('units', models.PositiveSmallIntegerField(default=1, verbose_name='сколько занятий убрано')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='removed_sessions', to='programs.prescription', verbose_name='назначение')),
            ],
            options={
                'verbose_name': 'убранное занятие',
                'verbose_name_plural': 'убранные занятия',
                'ordering': ['date'],
                'constraints': [models.UniqueConstraint(fields=('prescription', 'date'), name='removed_session_unique_date')],
            },
        ),
    ]
