# Generated by Django 5.2.17 on 2026-10-05 05:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0004_removed_session'),
        ('staff', '0002_shifts_and_duties'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='когда')),
                ('title', models.CharField(max_length=200, verbose_name='что изменилось')),
                ('items', models.JSONField(default=list, verbose_name='занятия')),
                ('reverted_at', models.DateTimeField(blank=True, null=True, verbose_name='возвращено')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='кто')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='changes', to='staff.instructor', verbose_name='инструктор')),
                ('reverted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='кто вернул')),
            ],
            options={
                'verbose_name': 'перестройка расписания',
                'verbose_name_plural': 'перестройки расписания',
                'ordering': ['-created_at'],
            },
        ),
    ]
