# Generated by Django 5.2.17 on 2026-10-05 16:55

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


def drop_weekend_individuals(apps, schema_editor):
    # Прототип ставил индивидуальные в выходные без инструктора (решение 56). В расписании v2
    # индивидуальные — только в шахматке по будням (TZ.md, FR-SCH-3).
    Booking = apps.get_model("scheduling", "Booking")
    Booking.objects.filter(kind="INDIVIDUAL", instructor__isnull=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_procedure_evening_individual'),
        ('programs', '0004_historicalprogram_preferred_instructor_and_more'),
        ('scheduling', '0005_staff_change'),
        ('staff', '0002_shifts_and_duties'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='дата')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='когда составлена')),
            ],
            options={
                'verbose_name': 'шахматка на дату',
                'verbose_name_plural': 'шахматки на дату',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='BoardPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='дата')),
                ('unplaced', models.PositiveSmallIntegerField(default=0, verbose_name='не распределено')),
                ('cancelled', models.PositiveSmallIntegerField(default=0, verbose_name='отменено')),
                ('edited', models.BooleanField(default=False, verbose_name='правили вручную')),
            ],
            options={
                'verbose_name': 'пациент в шахматке',
                'verbose_name_plural': 'пациенты в шахматке',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalBoardPatient',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('date', models.DateField(verbose_name='дата')),
                ('unplaced', models.PositiveSmallIntegerField(default=0, verbose_name='не распределено')),
                ('cancelled', models.PositiveSmallIntegerField(default=0, verbose_name='отменено')),
                ('edited', models.BooleanField(default=False, verbose_name='правили вручную')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical пациент в шахматке',
                'verbose_name_plural': 'historical пациенты в шахматке',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.RemoveConstraint(
            model_name='booking',
            name='booking_instructor_slot_unique',
        ),
        migrations.RemoveConstraint(
            model_name='booking',
            name='booking_instructor_only_individual',
        ),
        migrations.RunPython(drop_weekend_individuals, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('instructor__isnull', False), ('kind', 'INDIVIDUAL'), ('slot__isnull', False)), models.Q(models.Q(('kind', 'INDIVIDUAL'), _negated=True), ('instructor__isnull', True), ('slot__isnull', True)), _connector='OR'), name='booking_instructor_only_individual'),
        ),
        migrations.AddField(
            model_name='boardpatient',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_days', to='programs.program', verbose_name='программа'),
        ),
        migrations.AddField(
            model_name='historicalboardpatient',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalboardpatient',
            name='program',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='programs.program', verbose_name='программа'),
        ),
        migrations.AddConstraint(
            model_name='boardpatient',
            constraint=models.UniqueConstraint(fields=('date', 'program'), name='board_patient_unique'),
        ),
    ]
