# Generated by Django 5.2.17 on 2026-10-06 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0006_board_day'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StaffChange',
        ),
    ]
