# Generated by Django 5.2.17 on 2026-10-07 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0007_remove_staffchange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='kind',
            field=models.CharField(choices=[('LFK_GROUP', 'Lfk Group'), ('DS_GROUP', 'Ds Group'), ('POOL', 'Pool'), ('INDIVIDUAL', 'Individual'), ('EQUIPMENT', 'Equipment')], max_length=20, verbose_name='вид'),
        ),
        migrations.AlterField(
            model_name='historicalbooking',
            name='kind',
            field=models.CharField(choices=[('LFK_GROUP', 'Lfk Group'), ('DS_GROUP', 'Ds Group'), ('POOL', 'Pool'), ('INDIVIDUAL', 'Individual'), ('EQUIPMENT', 'Equipment')], max_length=20, verbose_name='вид'),
        ),
    ]
