# Generated by Django 5.2.17 on 2026-10-03 13:16

import apps.org.models
import django.core.validators
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='название')),
                ('code', models.SlugField(max_length=20, unique=True, verbose_name='код')),
                ('course_days', models.JSONField(default=apps.org.models.default_course_days, help_text='Например: {"3": 11, "4": 15, "5": 20}', verbose_name='длительность курса по ШРМ, дней')),
                ('max_individual_per_day', models.PositiveSmallIntegerField(default=2, validators=[django.core.validators.MinValueValidator(1)], verbose_name='индивидуальных занятий в день, не больше')),
                ('is_active', models.BooleanField(default=True, verbose_name='действует')),
            ],
            options={
                'verbose_name': 'отделение',
                'verbose_name_plural': 'отделения',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalDepartment',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='название')),
                ('code', models.SlugField(max_length=20, verbose_name='код')),
                ('course_days', models.JSONField(default=apps.org.models.default_course_days, help_text='Например: {"3": 11, "4": 15, "5": 20}', verbose_name='длительность курса по ШРМ, дней')),
                ('max_individual_per_day', models.PositiveSmallIntegerField(default=2, validators=[django.core.validators.MinValueValidator(1)], verbose_name='индивидуальных занятий в день, не больше')),
                ('is_active', models.BooleanField(default=True, verbose_name='действует')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical отделение',
                'verbose_name_plural': 'historical отделения',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
