# Generated by Django 5.2.17 on 2026-10-03 13:40

import datetime
import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('org', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='название')),
                ('window_start', models.TimeField(default=datetime.time(13, 0), verbose_name='окно с')),
                ('window_end', models.TimeField(default=datetime.time(15, 0), verbose_name='окно до')),
                ('step_min', models.PositiveSmallIntegerField(default=15, validators=[django.core.validators.MinValueValidator(1)], verbose_name='шаг записи, мин')),
                ('duration_min', models.PositiveSmallIntegerField(default=15, validators=[django.core.validators.MinValueValidator(1)], verbose_name='длительность, мин')),
                ('capacity', models.PositiveSmallIntegerField(default=1, help_text='Столько ставит подбор. Вручную можно записать больше — с пометкой.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='пациентов на одно время')),
                ('is_active', models.BooleanField(default=True, verbose_name='действует')),
            ],
            options={
                'verbose_name': 'тренажёр',
                'verbose_name_plural': 'тренажёры',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InstructorSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.TimeField(unique=True, verbose_name='начало')),
                ('end', models.TimeField(verbose_name='конец')),
                ('is_evening', models.BooleanField(default=False, help_text='Подбор не использует вечерние слоты — только ручная запись.', verbose_name='вечерний')),
            ],
            options={
                'verbose_name': 'слот инструкторов',
                'verbose_name_plural': 'сетка слотов инструкторов',
                'ordering': ['start'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalEquipment',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=60, verbose_name='название')),
                ('window_start', models.TimeField(default=datetime.time(13, 0), verbose_name='окно с')),
                ('window_end', models.TimeField(default=datetime.time(15, 0), verbose_name='окно до')),
                ('step_min', models.PositiveSmallIntegerField(default=15, validators=[django.core.validators.MinValueValidator(1)], verbose_name='шаг записи, мин')),
                ('duration_min', models.PositiveSmallIntegerField(default=15, validators=[django.core.validators.MinValueValidator(1)], verbose_name='длительность, мин')),
                ('capacity', models.PositiveSmallIntegerField(default=1, help_text='Столько ставит подбор. Вручную можно записать больше — с пометкой.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='пациентов на одно время')),
                ('is_active', models.BooleanField(default=True, verbose_name='действует')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical тренажёр',
                'verbose_name_plural': 'historical тренажёры',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalInstructorSlot',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('start', models.TimeField(db_index=True, verbose_name='начало')),
                ('end', models.TimeField(verbose_name='конец')),
                ('is_evening', models.BooleanField(default=False, help_text='Подбор не использует вечерние слоты — только ручная запись.', verbose_name='вечерний')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical слот инструкторов',
                'verbose_name_plural': 'historical сетка слотов инструкторов',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalProcedure',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название')),
                ('card_label', models.CharField(help_text='Например «Группа Эрго общая».', max_length=60, verbose_name='как печатается в карте')),
                ('synonyms', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, help_text='Как процедура пишется в листе назначений. Регистр, пробелы, точки и тире при сравнении не учитываются.', size=None, verbose_name='синонимы')),
                ('kind', models.CharField(choices=[('LFK_GROUP', 'Группа ЛФК'), ('POOL', 'Бассейн'), ('INDIVIDUAL', 'Индивидуальное занятие'), ('EQUIPMENT', 'Тренажёр'), ('CARD_ONLY', 'Только строка в карте')], max_length=20, verbose_name='вид')),
                ('default_duration_min', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='длительность по умолчанию, мин')),
                ('place', models.CharField(blank=True, max_length=60, verbose_name='место проведения')),
                ('is_active', models.BooleanField(default=True, verbose_name='действует')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('department', models.ForeignKey(blank=True, db_constraint=False, help_text='Пусто — процедура общая для всего центра.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='org.department', verbose_name='отделение')),
                ('equipment', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalog.equipment', verbose_name='тренажёр')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical процедура',
                'verbose_name_plural': 'historical процедуры',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название')),
                ('card_label', models.CharField(help_text='Например «Группа Эрго общая».', max_length=60, verbose_name='как печатается в карте')),
                ('synonyms', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, help_text='Как процедура пишется в листе назначений. Регистр, пробелы, точки и тире при сравнении не учитываются.', size=None, verbose_name='синонимы')),
                ('kind', models.CharField(choices=[('LFK_GROUP', 'Группа ЛФК'), ('POOL', 'Бассейн'), ('INDIVIDUAL', 'Индивидуальное занятие'), ('EQUIPMENT', 'Тренажёр'), ('CARD_ONLY', 'Только строка в карте')], max_length=20, verbose_name='вид')),
                ('default_duration_min', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='длительность по умолчанию, мин')),
                ('place', models.CharField(blank=True, max_length=60, verbose_name='место проведения')),
                ('is_active', models.BooleanField(default=True, verbose_name='действует')),
                ('department', models.ForeignKey(blank=True, help_text='Пусто — процедура общая для всего центра.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='procedures', to='org.department', verbose_name='отделение')),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='procedures', to='catalog.equipment', verbose_name='тренажёр')),
            ],
            options={
                'verbose_name': 'процедура',
                'verbose_name_plural': 'процедуры',
                'ordering': ['kind', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalGroupSession',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('start_time', models.TimeField(verbose_name='начало')),
                ('duration_min', models.PositiveSmallIntegerField(default=30, validators=[django.core.validators.MinValueValidator(1)], verbose_name='длительность, мин')),
                ('place', models.CharField(blank=True, help_text='Пусто — как у группы.', max_length=60, verbose_name='место проведения')),
                ('is_active', models.BooleanField(default=True, verbose_name='действует')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('procedure', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalog.procedure', verbose_name='группа')),
            ],
            options={
                'verbose_name': 'historical занятие группы',
                'verbose_name_plural': 'historical расписание групп',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='GroupSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(verbose_name='начало')),
                ('duration_min', models.PositiveSmallIntegerField(default=30, validators=[django.core.validators.MinValueValidator(1)], verbose_name='длительность, мин')),
                ('place', models.CharField(blank=True, help_text='Пусто — как у группы.', max_length=60, verbose_name='место проведения')),
                ('is_active', models.BooleanField(default=True, verbose_name='действует')),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='catalog.procedure', verbose_name='группа')),
            ],
            options={
                'verbose_name': 'занятие группы',
                'verbose_name_plural': 'расписание групп',
                'ordering': ['start_time', 'procedure__name'],
            },
        ),
        migrations.AddConstraint(
            model_name='procedure',
            constraint=models.UniqueConstraint(fields=('name', 'department'), name='unique_procedure_per_department', nulls_distinct=False),
        ),
        migrations.AddConstraint(
            model_name='groupsession',
            constraint=models.UniqueConstraint(fields=('procedure', 'start_time'), name='unique_session_start'),
        ),
    ]
