# Generated by Django 5.2.17 on 2026-10-04 13:25

from django.db import migrations, models


def mark_pool_without_sessions(apps, schema_editor):
    # Раньше «Бассейн» без группы определялся по отсутствию занятий — переносим это в признак.
    Procedure = apps.get_model("catalog", "Procedure")
    Procedure.objects.filter(kind="POOL", sessions__isnull=True).update(group_choice=True)


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprocedure',
            name='group_choice',
            field=models.BooleanField(default=False, help_text='Для «Бассейн» без группы: своего расписания нет, группу бассейна выбирает специалист ФР в расписании программы.', verbose_name='группу выбирает специалист ФР'),
        ),
        migrations.AddField(
            model_name='procedure',
            name='group_choice',
            field=models.BooleanField(default=False, help_text='Для «Бассейн» без группы: своего расписания нет, группу бассейна выбирает специалист ФР в расписании программы.', verbose_name='группу выбирает специалист ФР'),
        ),
        migrations.RunPython(mark_pool_without_sessions, migrations.RunPython.noop),
    ]
