# Generated by Django 5.2.17 on 2026-10-05 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_procedure_group_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprocedure',
            name='evening_individual',
            field=models.BooleanField(default=False, help_text='Проводится на одном из индивидуальных занятий пациента, только с 18:00. Своего расписания и строки в карте нет.', verbose_name='вечернее индивидуальное'),
        ),
        migrations.AddField(
            model_name='procedure',
            name='evening_individual',
            field=models.BooleanField(default=False, help_text='Проводится на одном из индивидуальных занятий пациента, только с 18:00. Своего расписания и строки в карте нет.', verbose_name='вечернее индивидуальное'),
        ),
    ]
