# Generated by Django 5.2.17 on 2026-10-07 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_procedure_evening_individual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprocedure',
            name='kind',
            field=models.CharField(choices=[('LFK_GROUP', 'Группа ЛФК'), ('DS_GROUP', 'Группа ДС'), ('POOL', 'Бассейн'), ('INDIVIDUAL', 'Индивидуальное занятие'), ('EQUIPMENT', 'Тренажёр'), ('CARD_ONLY', 'Только строка в карте')], max_length=20, verbose_name='вид'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='kind',
            field=models.CharField(choices=[('LFK_GROUP', 'Группа ЛФК'), ('DS_GROUP', 'Группа ДС'), ('POOL', 'Бассейн'), ('INDIVIDUAL', 'Индивидуальное занятие'), ('EQUIPMENT', 'Тренажёр'), ('CARD_ONLY', 'Только строка в карте')], max_length=20, verbose_name='вид'),
        ),
    ]
